Uploading to 7284bc4d7ead4ea74a43d4cd93074b91  838 / 838.0  (100.00%)
AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  queryIAM:
    Properties:
      CodeUri: s3://centralised-lambda-code-demo/7284bc4d7ead4ea74a43d4cd93074b91
      Description: ''
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::400731758471:role/lambda-query-iam
      Runtime: python3.6
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
